-- ------------------------------------------------------------------
-- Horizon Help Desk - canonical schema and seed data
-- State-reset checkpoint: drops and recreates all three tables.
-- Safe to re-run at any point in the workshop; it always restores
-- the exact state the labs expect (50 rows, 20 articles, 8 people).
-- ------------------------------------------------------------------
begin
  for t in (select table_name from user_tables
            where table_name in ('TICKETS','KB_ARTICLES','TEAM_MEMBERS')) loop
    execute immediate 'drop table ' || t.table_name || ' cascade constraints purge';
  end loop;
end;
/

create table team_members (
  id    number generated by default on null as identity (start with 1000) primary key,
  name  varchar2(100) not null,
  role  varchar2(50)  not null,
  email varchar2(255) not null
);

create table tickets (
  id          number generated by default on null as identity (start with 1000) primary key,
  subject     varchar2(200) not null,
  description varchar2(4000),
  status      varchar2(20) default 'Open' not null
              constraint tickets_status_ck check (status in ('Open','In Progress','Resolved','Closed')),
  priority    varchar2(10) default 'Medium' not null
              constraint tickets_priority_ck check (priority in ('Low','Medium','High','Critical')),
  category    varchar2(20) not null
              constraint tickets_category_ck check (category in ('Network','Hardware','Software','Access','Email')),
  created_on  date default sysdate not null,
  assigned_to number references team_members(id),
  reply       varchar2(4000)
);

create table kb_articles (
  id         number generated by default on null as identity (start with 1000) primary key,
  title      varchar2(200) not null,
  content    varchar2(4000) not null,
  category   varchar2(20) not null,
  updated_on date default sysdate not null,
  embedding  vector  -- populated in optional Lab 7; re-run its embed script after any schema reset
);

-- ---------- team members (8) ----------
insert into team_members (id, name, role, email) values (1, 'Ava Chen', 'Support Lead', 'ava.chen@example.com');
insert into team_members (id, name, role, email) values (2, 'Marcus Webb', 'Network Engineer', 'marcus.webb@example.com');
insert into team_members (id, name, role, email) values (3, 'Priya Nair', 'Support Analyst', 'priya.nair@example.com');
insert into team_members (id, name, role, email) values (4, 'Diego Ramos', 'Desktop Technician', 'diego.ramos@example.com');
insert into team_members (id, name, role, email) values (5, 'Hana Kobayashi', 'Support Analyst', 'hana.kobayashi@example.com');
insert into team_members (id, name, role, email) values (6, 'Tom Okafor', 'Access Administrator', 'tom.okafor@example.com');
insert into team_members (id, name, role, email) values (7, 'Lena Fischer', 'Email Administrator', 'lena.fischer@example.com');
insert into team_members (id, name, role, email) values (8, 'Sam Whitfield', 'Support Analyst', 'sam.whitfield@example.com');

-- ---------- knowledge base articles (20) ----------
insert into kb_articles (id, title, content, category, updated_on) values (1,
 'Clearing a stuck print queue (Windows spooler)',
 'When jobs hang in the queue: 1) Open Services and stop the Print Spooler service. 2) Delete all files in C:\Windows\System32\spool\PRINTERS. 3) Start the Print Spooler again and resubmit the job. If the same document re-jams the queue, update the printer driver before printing again.',
 'Hardware', date '2026-04-02');
insert into kb_articles (id, title, content, category, updated_on) values (2,
 'Resetting your password with self-service',
 'Go to the password portal, choose Forgot Password, and verify with your enrolled second factor. Choose a passphrase of at least 14 characters. Allow up to 5 minutes for the new password to sync to email and VPN before signing in again.',
 'Access', date '2026-03-18');
insert into kb_articles (id, title, content, category, updated_on) values (3,
 'Re-enrolling a lost or replaced MFA device',
 'A lost phone means your authenticator enrollment must be reset: 1) Manager opens an access request confirming your identity. 2) The access team revokes the old enrollment. 3) You re-enroll from the security portal on the new device. Codes from the old device stop working immediately after the reset.',
 'Access', date '2026-05-06');
insert into kb_articles (id, title, content, category, updated_on) values (4,
 'Mailbox is full: fixing email quota issues',
 'When the quota warning appears: empty Deleted Items, then use the mailbox cleanup tool to find messages over 10 MB and move attachments to your document share. Archives older than 18 months move automatically once online archive is enabled, which the email team can turn on within an hour.',
 'Email', date '2026-02-27');
insert into kb_articles (id, title, content, category, updated_on) values (5,
 'Freeing disk space when the C: drive is red',
 'Run Storage Sense with the "Temporary files" and "Previous Windows installations" options checked, then empty Downloads of installers. If the drive is still above 90 percent, the desktop team can extend the OS partition or issue a larger SSD for engineering laptops.',
 'Software', date '2026-01-30');
insert into kb_articles (id, title, content, category, updated_on) values (6,
 'Wi-Fi shows connected but no intranet: certificate renewal',
 'Corporate Wi-Fi uses a device certificate that expires yearly. If Wi-Fi connects but intranet sites fail: 1) Connect to the wired network or hotspot. 2) In Company Portal choose Sync to pull the renewed certificate. 3) Forget and rejoin the corporate SSID.',
 'Network', date '2026-06-11');
insert into kb_articles (id, title, content, category, updated_on) values (7,
 'Fixing VPN Error 812: remote access policy mismatch',
 'Error 812 means the RAS/VPN server rejected the connection because of an authentication policy mismatch. Fix: 1) Open the VPN client and select Settings > Security. 2) Change authentication from MS-CHAP v1 to MS-CHAP v2. 3) Reconnect. If the error persists after a recent password reset, wait 5 minutes for directory sync or reset the user''s dial-in policy in the admin console.',
 'Network', date '2026-05-14');
insert into kb_articles (id, title, content, category, updated_on) values (8,
 'Installing and updating the VPN client',
 'Install the VPN client only from Software Center; the vendor website build is not configured for our gateways. After install, import the profile file from the intranet security page and sign in with your network credentials plus MFA.',
 'Network', date '2026-04-22');
insert into kb_articles (id, title, content, category, updated_on) values (9,
 'Mapping the shared department drive',
 'In File Explorer choose Map network drive, pick a letter, and enter the department path from the storage directory page. Check "Reconnect at sign-in". If access is denied, your AD group membership is missing - raise an access request rather than a ticket.',
 'Access', date '2026-03-05');
insert into kb_articles (id, title, content, category, updated_on) values (10,
 'Installing approved software from Software Center',
 'All licensed software installs from Software Center without admin rights. Search the catalog, click Install, and allow up to 15 minutes. If an app you need is missing, submit a software request with a business justification; new titles are reviewed weekly.',
 'Software', date '2026-02-10');
insert into kb_articles (id, title, content, category, updated_on) values (11,
 'Docking station: no display or ethernet after undock',
 'Unplug the dock power for 30 seconds with the laptop disconnected, then reconnect power first and the laptop last. Update dock firmware from Software Center quarterly. Single-cable docks need the port marked with the lightning icon.',
 'Hardware', date '2026-05-28');
insert into kb_articles (id, title, content, category, updated_on) values (12,
 'Triage steps for a slow laptop',
 'Before raising a ticket: reboot fully (not sleep), check Task Manager for a runaway process, run Storage Sense, and confirm at least 15 percent free disk. If slowness persists across reboots, note the top process names in your ticket - it halves resolution time.',
 'Software', date '2026-01-19');
insert into kb_articles (id, title, content, category, updated_on) values (13,
 'Reporting phishing and suspicious email',
 'Use the Report Phish button in the mail client - it attaches full headers automatically. Never forward the message. If you clicked a link or entered credentials, call the security hotline immediately and reset your password from a known-good device.',
 'Email', date '2026-06-02');
insert into kb_articles (id, title, content, category, updated_on) values (14,
 'Delegating your calendar and shared mailboxes',
 'Calendar delegation is set under Calendar Settings > Shared calendars; grant Editor only to assistants who send on your behalf. Shared mailbox access is group-based - request the matching role in the access portal and it appears within 30 minutes.',
 'Email', date '2026-03-25');
insert into kb_articles (id, title, content, category, updated_on) values (15,
 'Breaking a single sign-on redirect loop',
 'An SSO loop (page keeps bouncing to the login screen) is almost always stale cookies: clear cookies for the company domain, close all browser windows, and sign in fresh. In private/incognito mode confirm it works, then clear the full cache if the normal window still loops.',
 'Software', date '2026-04-30');
insert into kb_articles (id, title, content, category, updated_on) values (16,
 'Pairing wireless keyboards and mice',
 'Put the device in pairing mode (hold the connect button 3 seconds), then add it under Bluetooth settings. Unifying-style receivers pair with the vendor utility in Software Center instead. Replace batteries before assuming the device is faulty - low battery causes cursor stutter.',
 'Hardware', date '2026-02-14');
insert into kb_articles (id, title, content, category, updated_on) values (17,
 'Fixing echo and robot voice on video calls',
 'Echo usually means the laptop mic and speakers are both live alongside a headset. Select the headset explicitly for BOTH microphone and speaker in the meeting app. Robot voice is bandwidth: turn off incoming video or move closer to the access point.',
 'Network', date '2026-05-20');
insert into kb_articles (id, title, content, category, updated_on) values (18,
 'Recovering deleted or overwritten files',
 'Check the Recycle Bin first, then right-click the folder and choose Restore previous versions for shared drives (snapshots kept 30 days). OneDrive files restore from the web portal''s recycle bin for 93 days. For anything older, raise a restore request with the exact path and date.',
 'Software', date '2026-06-18');
insert into kb_articles (id, title, content, category, updated_on) values (19,
 'How access requests and approvals work',
 'All permissions are group-based. Find the resource in the access portal, request the role, and your manager plus the resource owner approve. Provisioning is automatic after approval. Emergency access uses the break-glass process via the support lead, logged and time-boxed to 24 hours.',
 'Access', date '2026-04-08');
insert into kb_articles (id, title, content, category, updated_on) values (20,
 'Laptop battery drains too fast: health checks',
 'Generate a battery report (powercfg /batteryreport) and compare design vs full-charge capacity; below 60 percent qualifies for replacement. Meanwhile lower screen brightness, enable battery saver, and quit browser tabs playing media. Swollen batteries: stop using the laptop and contact hardware support the same day.',
 'Hardware', date '2026-03-12');

-- ---------- tickets (50) ----------
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (1,
 'Printer on floor 3 keeps jamming the queue', 'Print jobs pile up and nothing comes out. Restarting the printer did not help.', 'Resolved', 'Medium', 'Hardware', date '2026-06-01', 4);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (2,
 'Forgot password after vacation', 'Two weeks out of office and my password expired. Self-service says my second factor is not enrolled.', 'Closed', 'Medium', 'Access', date '2026-06-01', 6);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (3,
 'Mailbox full warning every morning', 'I keep getting quota warnings even after deleting old mail.', 'Resolved', 'Low', 'Email', date '2026-06-02', 7);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (4,
 'Laptop C: drive is completely red', 'Cannot install the monthly updates because the disk is full.', 'Closed', 'Medium', 'Software', date '2026-06-02', 4);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (5,
 'Wi-Fi connected but intranet unreachable', 'Internet works but internal sites time out since this morning.', 'Resolved', 'High', 'Network', date '2026-06-03', 2);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (6,
 'New starter needs shared drive access', 'Please add our new analyst to the finance shared drive group.', 'Closed', 'Medium', 'Access', date '2026-06-03', 6);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (7,
 'Cannot install approved IDE from Software Center', 'The install button spins for an hour and fails with code 0x87D00607.', 'Resolved', 'Medium', 'Software', date '2026-06-04', 5);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (8,
 'Docking station stopped detecting monitors', 'After undocking for a meeting both external screens stay black when I return.', 'Closed', 'Medium', 'Hardware', date '2026-06-04', 4);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (9,
 'Suspicious invoice email with attachment', 'Received an unexpected invoice from an unknown vendor, looks like phishing.', 'Resolved', 'Critical', 'Email', date '2026-06-05', 7);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (10,
 'Calendar delegation not working for assistant', 'My assistant cannot see meeting details even though I shared my calendar.', 'Resolved', 'Low', 'Email', date '2026-06-05', 7);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (11,
 'Laptop extremely slow after last update', 'Everything takes minutes to open since Tuesday''s patch cycle.', 'Resolved', 'Medium', 'Software', date '2026-06-08', 5);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (12,
 'VPN drops every hour on the hour', 'Connection re-authenticates hourly and drops my remote desktop session each time.', 'Resolved', 'Medium', 'Network', date '2026-06-08', 2);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (13,
 'MFA device lost with stolen bag', 'My phone with the authenticator app was stolen. I cannot log in to anything.', 'Closed', 'Critical', 'Access', date '2026-06-09', 6);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (14,
 'SSO login loop on the HR portal', 'The HR site keeps redirecting me back to the sign-in page in a loop.', 'Resolved', 'Medium', 'Software', date '2026-06-09', 3);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (15,
 'Wireless mouse cursor stutters constantly', 'Cursor freezes for a second at a time, very annoying during presentations.', 'Closed', 'Low', 'Hardware', date '2026-06-10', 4);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (16,
 'Echo complaints on all my video calls', 'Colleagues say they hear themselves whenever I speak.', 'Resolved', 'Low', 'Network', date '2026-06-10', 3);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (17,
 'Deleted quarterly report by accident', 'I overwrote the Q2 report on the shared drive with an empty file.', 'Resolved', 'High', 'Software', date '2026-06-11', 5);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (18,
 'Battery dies before lunch', 'Fully charged at 9am, dead by 11:30 even with light use.', 'Closed', 'Medium', 'Hardware', date '2026-06-11', 4);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (19,
 'Need access to the marketing analytics dashboard', 'Starting a new project and require viewer role on the analytics workspace.', 'Closed', 'Low', 'Access', date '2026-06-12', 6);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (20,
 'Shared mailbox missing after team move', 'Since moving teams I lost access to the support shared mailbox.', 'Resolved', 'Medium', 'Email', date '2026-06-12', 7);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (21,
 'Print jobs come out with garbled characters', 'Every PDF prints as random symbols on the legal team printer.', 'Resolved', 'Medium', 'Hardware', date '2026-06-15', 4);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (22,
 'Password reset link never arrives', 'Requested three reset emails, none delivered, checked spam.', 'Resolved', 'High', 'Access', date '2026-06-15', 6);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (23,
 'Attachment too large to send to client', 'Need to send a 40 MB proposal but mail bounces it.', 'Closed', 'Low', 'Email', date '2026-06-16', 7);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (24,
 'Video editing software request', 'Requesting the video suite for the comms team, not in Software Center catalog.', 'In Progress', 'Low', 'Software', date '2026-06-16', 5);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (25,
 'Conference room wifi dead spots', 'The large boardroom loses wifi at the far end of the table.', 'In Progress', 'Medium', 'Network', date '2026-06-17', 2);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (26,
 'Keyboard keys sticking after coffee spill', 'Spilled coffee on my laptop keyboard, several keys now stick.', 'Resolved', 'Medium', 'Hardware', date '2026-06-17', 4);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (27,
 'VPN error 812 on my new laptop', 'Got a replacement laptop yesterday and the VPN refuses to connect with error 812. The old laptop connected fine.', 'Open', 'Medium', 'Network', date '2026-06-18', 2);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (28,
 'Two-hour email delivery delays', 'Messages from external partners arrive hours late all week.', 'In Progress', 'High', 'Email', date '2026-06-18', 7);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (29,
 'Contractor offboarding access review', 'Please confirm all access for contractor batch C-2026-06 is revoked.', 'Closed', 'High', 'Access', date '2026-06-19', 6);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (30,
 'Laptop fan constantly at full speed', 'Fan screams even when idle, laptop hot to the touch.', 'Open', 'Medium', 'Hardware', date '2026-06-19', 4);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (31,
 'Cannot map the engineering shared drive', 'Access denied when mapping the drive letter even after the how-to.', 'Resolved', 'Medium', 'Access', date '2026-06-22', 6);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (32,
 'Spreadsheet add-in crashes on open', 'The reporting add-in crashes the spreadsheet app on launch since Friday.', 'In Progress', 'Medium', 'Software', date '2026-06-22', 5);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (33,
 'Monitor flickers at 120Hz', 'New external monitor flickers unless I drop refresh rate to 60.', 'Open', 'Low', 'Hardware', date '2026-06-23', 4);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (34,
 'Newsletter marked as spam for all staff', 'The internal newsletter lands in everyone''s junk folder.', 'Resolved', 'Low', 'Email', date '2026-06-23', 7);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (35,
 'Cannot reach intranet over VPN', 'VPN connects but intranet pages time out; public internet fine. Started after the gateway maintenance window.', 'In Progress', 'High', 'Network', date '2026-06-24', 2);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (36,
 'Build server access for new developer', 'Add developer role on the CI environment for our new hire.', 'Open', 'Medium', 'Access', date '2026-06-24', 6);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (37,
 'License expired popup on CAD software', 'CAD tool says license expired although we renewed last month.', 'Open', 'High', 'Software', date '2026-06-25', 5);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (38,
 'Headset microphone not detected', 'USB headset plays audio but the mic never appears in settings.', 'Resolved', 'Low', 'Hardware', date '2026-06-25', 4);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (39,
 'Wrong name on email display', 'My display name still shows my maiden name after HR updated records.', 'Open', 'Low', 'Email', date '2026-06-26', 7);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (40,
 'Guest wifi vouchers for customer visit', 'Need 25 guest wifi vouchers for the customer workshop next Wednesday.', 'Closed', 'Medium', 'Network', date '2026-06-26', 2);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (41,
 'Files missing from project folder', 'A whole subfolder of the project drive vanished overnight.', 'In Progress', 'Critical', 'Software', date '2026-06-29', 5);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (42,
 'Cannot connect to VPN - error 812 when working from home', 'User reports VPN fails with error 812 every time they connect from their home network. Started right after Monday''s password reset.', 'Open', 'High', 'Network', date '2026-07-01', 3);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (43,
 'Laptop won''t power on after weekend', 'No lights, no fan, tried holding power 30 seconds and a different charger.', 'Open', 'Critical', 'Hardware', date '2026-07-01', 4);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (44,
 'Read receipt requests to entire org', 'Someone''s mail rule is requesting read receipts from all-staff replies.', 'Open', 'Low', 'Email', date '2026-07-02', 7);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (45,
 'Temporary admin rights for driver install', 'Field engineer needs elevated rights to install a lab instrument driver.', 'In Progress', 'Medium', 'Access', date '2026-07-02', 6);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (46,
 'Browser crashes on the expense portal', 'Submitting an expense report crashes the tab every time.', 'Open', 'Medium', 'Software', date '2026-07-03', 5);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (47,
 'Desk phone not registering after move', 'Moved desks and the IP phone shows registering forever.', 'Open', 'Low', 'Network', date '2026-07-03', 2);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (48,
 'Second monitor requested for accessibility', 'Occupational health recommended a second screen for my workstation.', 'Open', 'Medium', 'Hardware', date '2026-07-04', 4);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (49,
 'Mail rules disappeared after client update', 'All my inbox sorting rules vanished after yesterday''s mail client update.', 'Open', 'Medium', 'Email', date '2026-07-04', 7);
insert into tickets (id, subject, description, status, priority, category, created_on, assigned_to) values (50,
 'Quarterly access recertification overdue', 'Manager dashboard shows 12 access reviews pending past the deadline.', 'Open', 'High', 'Access', date '2026-07-05', 6);

commit;
